# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: '$(BuildID).$(date:yyMMdd)'

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pool:
  vmImage: ubuntu-latest

variables:
  versionNumber: '0.1.$(Build.BuildNumber)'

stages:
- stage: build
  displayName: build
  jobs:
  - job: build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm ci
        npm run build
      displayName: 'npm install and build'
    
    - task: PublishPipelineArtifact@1
      inputs:
        ArtifactName: 'drop'
        targetPath: '$(Build.SourcesDirectory)/dist'

- stage: pr
  displayName: pr
  condition: and(succeeded(), eq(variables['system.pullrequest.targetbranch'], 'refs/heads/master'))
  dependsOn:
  - build
  jobs:
  - deployment: prdeploy
    displayName: prDeploy
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 1
    environment: chiabee-pr
    strategy:
      runOnce:
        deploy:
          steps:
          - task: FtpUpload@2
            inputs:
              credentialsOption: 'serviceEndpoint'
              serverEndpoint: 'chiabee_client_pr_ftp'
              rootDirectory: '$(Pipeline.Workspace)/drop'
              filePatterns: '**'
              remoteDirectory: '/'
              clean: false
              cleanContents: false
              preservePaths: true
              trustSSL: false