# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: '$(BuildID).$(date:yyMMdd)'

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pool:
  vmImage: ubuntu-latest

variables:
  versionNumber: '0.1.$(Build.BuildNumber)'
  devEnvironment: 'chiabee-dev'
  qaEnvironment: 'chiabee-qa'
  prodEnvironment: 'chiabee-prod'

stages:
- stage: build
  displayName: build
  jobs:
  - job: build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'
    
    - task: PublishPipelineArtifact@1
      inputs:
        ArtifactName: 'drop'
        targetPath: '$(Pipeline.Workspace)'
